name: Deploy_To_Blob_NG_Dev

on:
  push:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "**/README.md" # don't run on README.md file updates anywhere in repo
      - "**/dependabot.yml"
    branches:
      - unified-platform-migration # eventually update to develop

env:
  STAGE: dev # prefix to indicate environment stage
  NAME: iati-validator-web
  STORAGE_NAME: deviativalidatorweb
  CI: 1
  CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RESOURCE_GROUP: dev-iati-resources

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install --ignore-scripts

      - name: Run build
        run: |
          npm run build

      - name: Install @azure/ng-deploy
        run: ng add @azure/ng-deploy -m \
          --subscription-id ${{ env.AZURE_SUBSCRIPTION_ID }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --account ${{ env.STORAGE_NAME}} \
          --location 'UK South'

      - name: Deploy to Azure Storage Blob
        run: ng run dqf-app:deploy
