name: Deploy_To_Azure_Blobs_NG_Dev

on:
  push:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "**/README.md" # don't run on README.md file updates anywhere in repo
      - "**/dependabot.yml"
    branches:
      - develop # eventually update to develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.4.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --ignore-scripts

      - name: Copy environment specific env.js file
        run: |
          cp src/env.dev.js src/env.js

      - name: Run build
        run: |
          npm run build:dev

      - name: Create 404
        run: cp dist/index.html dist/404.html

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        env: 
          STORAGE_NAME: savalidatorwebdev
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch --account-name ${{ env.STORAGE_NAME }} --auth-mode key -d '$web' -s dist/
