name: Build_Test_NG_Dev

on:
  pull_request:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - '**/README.md'
      - '**/dependabot.yml'
      - '.github/workflows/develop_CD.yml'
      - '.github/workflows/main_CD.yml'
    branches:
      - develop

concurrency: develop_CI

jobs:
  test-build:
    name: "Test & Build"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --ignore-scripts
          npm install -g codecov

      - name: Run tests
        run: |
          npm run lint
        env:
          CI: true

      - name: Run build
        run: |
          npm run build:prod
        env:
          CI: true

  automerge:
      needs: test-build
      runs-on: ubuntu-latest
      permissions:
        pull-requests: write
        contents: write
      steps:
        - uses: fastify/github-action-merge-dependabot@v3.5.3
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
