name: Deploy_To_Blob_NG_Dev

on:
  push:
    paths-ignore: # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
      - "**/README.md" # don't run on README.md file updates anywhere in repo
      - "**/dependabot.yml"
    branches:
      - unified-platform-migration # eventually update to develop

env:
  STORAGE_NAME: deviativalidatorweb
  CI: 1
  CLIENT_ID: ${{ secrets.DEV_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.DEV_CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm install --ignore-scripts
          npm install -g @angular/cli

      - name: Run build
        run: |
          npm run build

      - name: Install @azure/ng-deploy
        run: |
          ng add @azure/ng-deploy -m -i ${{ env.AZURE_SUBSCRIPTION_ID }} -a ${{ env.STORAGE_NAME }} -g dev-iati-resources -l 'UK South'

      - name: Deploy to Azure Storage Blob
        run: ng run dqf-app:deploy
