name: Deploy_To_Production_Blob_on_Release

# Runs when a Release is published from GitHub UI
on:
  release:
    types: [published]

env:
  STORAGE_ACCOUNT_NAME: savalidatorwebprod
  STORAGE_ACCOUNT_KEY: ${{ secrets.PROD_STORAGE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3.0.0
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install --ignore-scripts

      - name: Copy environment specific env.js file
        run: |
          cp src/env.prod.js src/env.js

      - name: Run build
        run: |
          npm run build:prod

      - name: Create 404
        run: cp dist/index.html dist/404.html

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          azcliversion: 2.34.0
          inlineScript: |
            az storage blob upload-batch \
            --overwrite true \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --account-key ${{ env.STORAGE_ACCOUNT_KEY }} \
            -d '$web' \
            -s dist/
